export const Items = [
  {
    id: 1,
    type: 'shoes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 1',
    description: 'Item 1 Description',
    price: 100,
  },
  {
    id: 2,
    type: 'jewelry',
    url: 'https://via.placeholder.com/150',
    name: 'Item 2',
    description: 'Item 2 Description',
    price: 200,
  },
  {
    id: 3,
    type: 'dishes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 3',
    description: 'Item 3 Description',
    price: 300,
  },
  {
    id: 4,
    type: 'art',
    url: 'https://via.placeholder.com/150',
    name: 'Item 4',
    description: 'Item 4 Description',
    price: 400,
  },
  {
    id: 5,
    type: 'shoes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 5',
    description: 'Item 5 Description',
    price: 500,
  },
  {
    id: 6,
    type: 'jewelry',
    url: 'https://via.placeholder.com/150',
    name: 'Item 6',
    description: 'Item 6 Description',
    price: 600,
  },
  {
    id: 7,
    type: 'dishes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 7',
    description: 'Item 7 Description',
    price: 700,
  },
  {
    id: 8,
    type: 'art',
    url: 'https://via.placeholder.com/150',
    name: 'Item 8',
    description: 'Item 8 Description',
    price: 800,
  },
  {
    id: 9,
    type: 'shoes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 9',
    description: 'Item 9 Description',
    price: 900,
  },
  {
    id: 10,
    type: 'jewelry',
    url: 'https://via.placeholder.com/150',
    name: 'Item 10',
    description: 'Item 10 Description',
    price: 1000,
  },
  {
    id: 11,
    type: 'dishes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 11',
    description: 'Item 11 Description',
    price: 1100,
  },
  {
    id: 12,
    type: 'art',
    url: 'https://via.placeholder.com/150',
    name: 'Item 12',
    description: 'Item 12 Description',
    price: 1200,
  },
  {
    id: 13,
    type: 'shoes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 13',
    description: 'Item 13 Description',
    price: 1300,
  },
  {
    id: 14,
    type: 'jewelry',
    url: 'https://via.placeholder.com/150',
    name: 'Item 14',
    description: 'Item 14 Description',
    price: 1400,
  },
  {
    id: 15,
    type: 'dishes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 15',
    description: 'Item 15 Description',
    price: 1500,
  },
  {
    id: 16,
    type: 'art',
    url: 'https://via.placeholder.com/150',
    name: 'Item 16',
    description: 'Item 16 Description',
    price: 1600,
  },
  {
    id: 17,
    type: 'shoes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 17',
    description: 'Item 17 Description',
    price: 1700,
  },
  {
    id: 18,
    type: 'jewelry',
    url: 'https://via.placeholder.com/150',
    name: 'Item 18',
    description: 'Item 18 Description',
    price: 1800,
  },
  {
    id: 19,
    type: 'dishes',
    url: 'https://via.placeholder.com/150',
    name: 'Item 19',
    description: 'Item 19 Description',
    price: 1900,
  },
  {
    id: 20,
    type: 'art',
    url: 'https://via.placeholder.com/150',
    name: 'Item 20',
    description: 'Item 20 Description',
    price: 2000,
  },
];
